language: csharp

env:
 - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis TRAVIS_STAGE=0 # DISABLE_NETCORE=true
 - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis TRAVIS_STAGE=1 # DISABLE_NETCORE=true

# dependencies (netcore)
addons:
  apt:
    packages:
       - libunwind8

sudo: false  # use the new container-based Travis infrastructure
#sudo: required
dist: trusty # Ubuntu 14.04

mono:
  - nightly
  - latest
#  - 5.2.0 Note: 5.2 is really unstable, no sense in wasting build resources

branches:
  except:
    - gh-pages

script: 
  - ./build.sh RunIntegrationTests
