language: csharp
dist: trusty

sudo: false

env:
  global:
    - HOME=/home/travis
    - APPDATA=/home/travis
    - LocalAppData=/home/travis
  matrix:
    # run .net integration tests
    - SkipIntegrationTestsNetCore=true PAKET_TESTSUITE_FLAKYTESTS=false
    # run .net core integration tests
    - SkipIntegrationTestsNet=true PAKET_TESTSUITE_FLAKYTESTS=false
    # just flaky tests
    - PAKET_TESTSUITE_FLAKYTESTS=true

dotnet: 2.1.401

mono:
  - 5.12.0
  - 5.10.0
  - 5.8.1
  - latest

matrix:
  allow_failures:
    # travis failure to install mono (ref https://github.com/travis-ci/travis-ci/issues/9171)
    - mono: latest
    # flaky test are expected to fail from time to time
    - env: PAKET_TESTSUITE_FLAKYTESTS=true
    # sporadic MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
    - env: SkipIntegrationTestsNetCore=true PAKET_TESTSUITE_FLAKYTESTS=false

branches:
  except:
    - gh-pages

script:
  - ./build.sh BuildPackage
