image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildPackage
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: 'temp\*.nupkg'
    type: NuGetPackage
nuget:
  account_feed: false
  project_feed: true

#environment:
#  # these variables are common to all jobs
#  #common_var1: value1
#
#  matrix:
#    # first group
#    - SkipIntegrationTests: true
#    # second group
#    - SkipNuGet: true

